import * as path from "path";
export type JsType = "string" | "number" | "boolean";
export interface ModuleSpec { script: string; argsSchema: Record<string, JsType>; timeoutSec?: number; }

// Use dynamic path resolution instead of hardcoded path
// Determine base directory: if running from guiv2, go up one level; otherwise use cwd
const cwd = process.cwd();
const baseDir = cwd.endsWith('guiv2') ? path.join(cwd, '..') : cwd;
const ROOT = path.join(baseDir, "Modules"); // Capital M to match actual directory

export const DiscoveryModules: Record<string, ModuleSpec> = {
  ActiveDirectory: { script: path.join(ROOT, "Discovery", "ActiveDirectoryDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  Application: { script: path.join(ROOT, "Discovery", "Application.psm1"), argsSchema: {} },
  ApplicationDependencyMapping: { script: path.join(ROOT, "Discovery", "ApplicationDependencyMapping.psm1"), argsSchema: {} },
  ApplicationDiscovery: { script: path.join(ROOT, "Discovery", "ApplicationDiscovery.psm1"), argsSchema: {} },
  AWS: { script: path.join(ROOT, "Discovery", "AWSDiscovery.psm1"), argsSchema: {} },
  Azure: { script: path.join(ROOT, "Discovery", "AzureDiscovery.psm1"), argsSchema: {} },
  AzureResource: { script: path.join(ROOT, "Discovery", "AzureResourceDiscovery.psm1"), argsSchema: {} },
  BackupRecovery: { script: path.join(ROOT, "Discovery", "BackupRecoveryDiscovery.psm1"), argsSchema: {} },
  CertificateAuthority: { script: path.join(ROOT, "Discovery", "CertificateAuthorityDiscovery.psm1"), argsSchema: {} },
  Certificate: { script: path.join(ROOT, "Discovery", "CertificateDiscovery.psm1"), argsSchema: {} },
  ConcurrentDiscoveryEngine: { script: path.join(ROOT, "Discovery", "ConcurrentDiscoveryEngine.psm1"), argsSchema: {} },
  ConditionalAccess: { script: path.join(ROOT, "Discovery", "ConditionalAccessDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  DatabaseSchema: { script: path.join(ROOT, "Discovery", "DatabaseSchemaDiscovery.psm1"), argsSchema: {} },
  DataClassification: { script: path.join(ROOT, "Discovery", "DataClassification.psm1"), argsSchema: {} },
  DataClassificationDiscovery: { script: path.join(ROOT, "Discovery", "DataClassificationDiscovery.psm1"), argsSchema: {} },
  DiscoveryBase: { script: path.join(ROOT, "Discovery", "DiscoveryBase.psm1"), argsSchema: {} },
  DiscoveryModuleBase: { script: path.join(ROOT, "Discovery", "DiscoveryModuleBase.psm1"), argsSchema: {} },
  DLP: { script: path.join(ROOT, "Discovery", "DLPDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  DNSDHCP: { script: path.join(ROOT, "Discovery", "DNSDHCPDiscovery.psm1"), argsSchema: {} },
  EntraIDApp: { script: path.join(ROOT, "Discovery", "EntraIDApp.psm1"), argsSchema: {} },
  EntraIDAppDiscovery: { script: path.join(ROOT, "Discovery", "EntraIDAppDiscovery.psm1"), argsSchema: {} },
  EnvironmentDetection: { script: path.join(ROOT, "Discovery", "EnvironmentDetectionDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  Exchange: { script: path.join(ROOT, "Discovery", "ExchangeDiscovery.psm1"), argsSchema: {} },
  ExternalIdentity: { script: path.join(ROOT, "Discovery", "ExternalIdentity.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  ExternalIdentityDiscovery: { script: path.join(ROOT, "Discovery", "ExternalIdentityDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  FileServer: { script: path.join(ROOT, "Discovery", "FileServer.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  FileServerDiscovery: { script: path.join(ROOT, "Discovery", "FileServerDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  FileSystem: { script: path.join(ROOT, "Discovery", "FileSystemDiscovery.psm1"), argsSchema: {} },
  GCP: { script: path.join(ROOT, "Discovery", "GCPDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  GPO: { script: path.join(ROOT, "Discovery", "GPODiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  Graph: { script: path.join(ROOT, "Discovery", "GraphDiscovery.psm1"), argsSchema: {} },
  Infrastructure: { script: path.join(ROOT, "Discovery", "InfrastructureDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  Intune: { script: path.join(ROOT, "Discovery", "IntuneDiscovery.psm1"), argsSchema: {} },
  Licensing: { script: path.join(ROOT, "Discovery", "Licensing.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  LicensingDiscovery: { script: path.join(ROOT, "Discovery", "LicensingDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  MultiDomainForest: { script: path.join(ROOT, "Discovery", "MultiDomainForest.psm1"), argsSchema: {} },
  MultiDomainForestDiscovery: { script: path.join(ROOT, "Discovery", "MultiDomainForestDiscovery.psm1"), argsSchema: {} },
  NetworkInfrastructure: { script: path.join(ROOT, "Discovery", "NetworkInfrastructure.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  NetworkInfrastructureDiscovery: { script: path.join(ROOT, "Discovery", "NetworkInfrastructureDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  OneDrive: { script: path.join(ROOT, "Discovery", "OneDriveDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  PaloAlto: { script: path.join(ROOT, "Discovery", "PaloAltoDiscovery.psm1"), argsSchema: {} },
  PanoramaInterrogation: { script: path.join(ROOT, "Discovery", "PanoramaInterrogation.psm1"), argsSchema: {} },
  PhysicalServer: { script: path.join(ROOT, "Discovery", "PhysicalServer.psm1"), argsSchema: {} },
  PhysicalServerDiscovery: { script: path.join(ROOT, "Discovery", "PhysicalServerDiscovery.psm1"), argsSchema: {} },
  PowerBI: { script: path.join(ROOT, "Discovery", "PowerBIDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  PowerPlatform: { script: path.join(ROOT, "Discovery", "PowerPlatformDiscovery.psm1"), argsSchema: {} },
  Printer: { script: path.join(ROOT, "Discovery", "PrinterDiscovery.psm1"), argsSchema: {} },
  RealTimeDiscoveryEngine: { script: path.join(ROOT, "Discovery", "RealTimeDiscoveryEngine.psm1"), argsSchema: {} },
  ScheduledTask: { script: path.join(ROOT, "Discovery", "ScheduledTaskDiscovery.psm1"), argsSchema: {} },
  SecurityGroupAnalysis: { script: path.join(ROOT, "Discovery", "SecurityGroupAnalysis.psm1"), argsSchema: {} },
  SecurityInfrastructure: { script: path.join(ROOT, "Discovery", "SecurityInfrastructureDiscovery.psm1"), argsSchema: {} },
  SharePoint: { script: path.join(ROOT, "Discovery", "SharePointDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  SQLServer: { script: path.join(ROOT, "Discovery", "SQLServer.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  SQLServerDiscovery: { script: path.join(ROOT, "Discovery", "SQLServerDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  StorageArray: { script: path.join(ROOT, "Discovery", "StorageArrayDiscovery.psm1"), argsSchema: {} },
  Teams: { script: path.join(ROOT, "Discovery", "TeamsDiscovery.psm1"), argsSchema: {"Message":"string","Level":"string","Component":"string","Context":"string"} },
  Virtualization: { script: path.join(ROOT, "Discovery", "Virtualization.psm1"), argsSchema: {} },
  VirtualizationDiscovery: { script: path.join(ROOT, "Discovery", "VirtualizationDiscovery.psm1"), argsSchema: {} },
  VMware: { script: path.join(ROOT, "Discovery", "VMwareDiscovery.psm1"), argsSchema: {} },
  WebServerConfig: { script: path.join(ROOT, "Discovery", "WebServerConfigDiscovery.psm1"), argsSchema: {} },
};

export const MigrationModules: Record<string, ModuleSpec> = {
  Application: { script: path.join(ROOT, "Migration", "ApplicationMigration.psm1"), argsSchema: {} },
  FileSystem: { script: path.join(ROOT, "Migration", "FileSystemMigration.psm1"), argsSchema: {} },
  Mailbox: { script: path.join(ROOT, "Migration", "MailboxMigration.psm1"), argsSchema: {} },
  MailboxMigrationBackup: { script: path.join(ROOT, "Migration", "MailboxMigration_backup.psm1"), argsSchema: {} },
  Server: { script: path.join(ROOT, "Migration", "ServerMigration.psm1"), argsSchema: {} },
  SharePoint: { script: path.join(ROOT, "Migration", "SharePointMigration.psm1"), argsSchema: {} },
  SharePointMigrationEnhanced: { script: path.join(ROOT, "Migration", "SharePointMigration_Enhanced.psm1"), argsSchema: {} },
  User: { script: path.join(ROOT, "Migration", "UserMigration.psm1"), argsSchema: {} },
  UserProfile: { script: path.join(ROOT, "Migration", "UserProfileMigration.psm1"), argsSchema: {} },
  VirtualMachine: { script: path.join(ROOT, "Migration", "VirtualMachineMigration.psm1"), argsSchema: {} },
};
