using System.Windows;
using System.Windows.Controls;

namespace MandADiscoverySuite.Views
{
    public partial class AssetDetailWindow : Window
    {
        public AssetDetailWindow()
        {
            InitializeComponent();
        }

        private void CloseButton_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        /// <summary>
        /// InitializeComponent implementation - generated by XAML compiler
        /// </summary>
        private void InitializeComponent()
        {
            this.Loaded += AssetDetailWindow_Loaded;
            this.Title = "Asset Details";
            this.Height = 800;
            this.Width = 1200;
            this.WindowStartupLocation = WindowStartupLocation.CenterOwner;
            this.ShowInTaskbar = false;
            this.Background = (System.Windows.Media.Brush)System.Windows.Application.Current.Resources["BackgroundBrush"];

            // Create the main Grid
            var mainGrid = new Grid();

            // Embed the AssetDetailView UserControl
            var assetDetailView = new AssetDetailView();
            mainGrid.Children.Add(assetDetailView);
            Grid.SetColumn(assetDetailView, 0);
            Grid.SetRow(assetDetailView, 0);

            this.Content = mainGrid;
        }

        private void AssetDetailWindow_Loaded(object sender, RoutedEventArgs e)
        {
            // Add any initialization logic here if needed
        }
    }
}