/**
 * Certificates Discovered View
 *
 * Auto-generated discovered data view for Certificates.
 * Displays CSV data from: CertificatesDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module certificates
 * @category security
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Certificates discovered data view component
 */
export const CertificatesDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Certificates"
      csvPath="CertificatesDiscovery.csv"
      title="Certificates"
      description="SSL/TLS certificates and certificate inventory"
      enableSearch={true}
      enableExport={true}
      data-cy="certificates-discovered-view"
    />
  );
};

export default CertificatesDiscoveredView;


