/**
 * Hyper-V Discovered View
 *
 * Auto-generated discovered data view for Hyper-V.
 * Displays CSV data from: HyperVDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module hyperv
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Hyper-V discovered data view component
 */
export const HypervDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Hyper-V"
      csvPath="HyperVDiscovery.csv"
      title="Hyper-V"
      description="Hyper-V virtual machines and host configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="hyperv-discovered-view"
    />
  );
};

export default HypervDiscoveredView;


