/**
 * OneDrive Discovered View
 *
 * Auto-generated discovered data view for OneDrive.
 * Displays CSV data from: OneDriveDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module onedrive
 * @category collaboration
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * OneDrive discovered data view component
 */
export const OnedriveDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="OneDrive"
      csvPath="OneDriveDiscovery.csv"
      title="OneDrive"
      description="OneDrive storage, sharing, and sync configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="onedrive-discovered-view"
    />
  );
};

export default OnedriveDiscoveredView;


