/**
 * SharePoint Discovered View
 *
 * Auto-generated discovered data view for SharePoint.
 * Displays CSV data from: SharePointSites.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module sharepoint
 * @category collaboration
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * SharePoint discovered data view component
 */
export const SharepointDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="SharePoint"
      csvPath="SharePointSites.csv"
      title="SharePoint"
      description="SharePoint sites, libraries, and permissions"
      enableSearch={true}
      enableExport={true}
      data-cy="sharepoint-discovered-view"
    />
  );
};

export default SharepointDiscoveredView;


