// Auto-generated discovered view routes
// Generated by: scripts/generate-discovery-views.js
// Do not edit manually - regenerate using: npm run generate:views

import { lazy } from 'react';

const ActivedirectoryDiscoveredView = lazy(() => import('./views/discovered/ActivedirectoryDiscoveredView'));
const ApplicationsDiscoveredView = lazy(() => import('./views/discovered/ApplicationsDiscoveredView'));
const AwsDiscoveredView = lazy(() => import('./views/discovered/AwsDiscoveredView'));
const AzureDiscoveredView = lazy(() => import('./views/discovered/AzureDiscoveredView'));
const AzureresourceDiscoveredView = lazy(() => import('./views/discovered/AzureresourceDiscoveredView'));
const BackuprecoveryDiscoveredView = lazy(() => import('./views/discovered/BackuprecoveryDiscoveredView'));
const CertificateauthorityDiscoveredView = lazy(() => import('./views/discovered/CertificateauthorityDiscoveredView'));
const CertificatesDiscoveredView = lazy(() => import('./views/discovered/CertificatesDiscoveredView'));
const ConditionalaccessDiscoveredView = lazy(() => import('./views/discovered/ConditionalaccessDiscoveredView'));
const DatabaseschemaDiscoveredView = lazy(() => import('./views/discovered/DatabaseschemaDiscoveredView'));
const DataclassificationDiscoveredView = lazy(() => import('./views/discovered/DataclassificationDiscoveredView'));
const DnsdhcpDiscoveredView = lazy(() => import('./views/discovered/DnsdhcpDiscoveredView'));
const EntraidappDiscoveredView = lazy(() => import('./views/discovered/EntraidappDiscoveredView'));
const EnvironmentdetectionDiscoveredView = lazy(() => import('./views/discovered/EnvironmentdetectionDiscoveredView'));
const ExchangeDiscoveredView = lazy(() => import('./views/discovered/ExchangeDiscoveredView'));
const ExternalidentityDiscoveredView = lazy(() => import('./views/discovered/ExternalidentityDiscoveredView'));
const FileserverDiscoveredView = lazy(() => import('./views/discovered/FileserverDiscoveredView'));
const FilesystemDiscoveredView = lazy(() => import('./views/discovered/FilesystemDiscoveredView'));
const GcpDiscoveredView = lazy(() => import('./views/discovered/GcpDiscoveredView'));
const GpoDiscoveredView = lazy(() => import('./views/discovered/GpoDiscoveredView'));
const GraphDiscoveredView = lazy(() => import('./views/discovered/GraphDiscoveredView'));
const InfrastructureDiscoveredView = lazy(() => import('./views/discovered/InfrastructureDiscoveredView'));
const IntuneDiscoveredView = lazy(() => import('./views/discovered/IntuneDiscoveredView'));
const LicensingDiscoveredView = lazy(() => import('./views/discovered/LicensingDiscoveredView'));
const MultidomainforestDiscoveredView = lazy(() => import('./views/discovered/MultidomainforestDiscoveredView'));
const NetworkinfrastructureDiscoveredView = lazy(() => import('./views/discovered/NetworkinfrastructureDiscoveredView'));
const OnedriveDiscoveredView = lazy(() => import('./views/discovered/OnedriveDiscoveredView'));
const PaloaltoDiscoveredView = lazy(() => import('./views/discovered/PaloaltoDiscoveredView'));
const PhysicalserverDiscoveredView = lazy(() => import('./views/discovered/PhysicalserverDiscoveredView'));
const PowerbiDiscoveredView = lazy(() => import('./views/discovered/PowerbiDiscoveredView'));
const PowerplatformDiscoveredView = lazy(() => import('./views/discovered/PowerplatformDiscoveredView'));
const PrintersDiscoveredView = lazy(() => import('./views/discovered/PrintersDiscoveredView'));
const ScheduledtasksDiscoveredView = lazy(() => import('./views/discovered/ScheduledtasksDiscoveredView'));
const SecurityinfrastructureDiscoveredView = lazy(() => import('./views/discovered/SecurityinfrastructureDiscoveredView'));
const SharepointDiscoveredView = lazy(() => import('./views/discovered/SharepointDiscoveredView'));
const SqlserverDiscoveredView = lazy(() => import('./views/discovered/SqlserverDiscoveredView'));
const StoragearrayDiscoveredView = lazy(() => import('./views/discovered/StoragearrayDiscoveredView'));
const TeamsDiscoveredView = lazy(() => import('./views/discovered/TeamsDiscoveredView'));
const VirtualizationDiscoveredView = lazy(() => import('./views/discovered/VirtualizationDiscoveredView'));
const VmwareDiscoveredView = lazy(() => import('./views/discovered/VmwareDiscoveredView'));
const WebserverconfigDiscoveredView = lazy(() => import('./views/discovered/WebserverconfigDiscoveredView'));
const HypervDiscoveredView = lazy(() => import('./views/discovered/HypervDiscoveredView'));

export const discoveredRoutes = [
  {
    path: '/discovered/activedirectory',
    element: <ActivedirectoryDiscoveredView />
  },
  {
    path: '/discovered/applications',
    element: <ApplicationsDiscoveredView />
  },
  {
    path: '/discovered/aws',
    element: <AwsDiscoveredView />
  },
  {
    path: '/discovered/azure',
    element: <AzureDiscoveredView />
  },
  {
    path: '/discovered/azureresource',
    element: <AzureresourceDiscoveredView />
  },
  {
    path: '/discovered/backuprecovery',
    element: <BackuprecoveryDiscoveredView />
  },
  {
    path: '/discovered/certificateauthority',
    element: <CertificateauthorityDiscoveredView />
  },
  {
    path: '/discovered/certificates',
    element: <CertificatesDiscoveredView />
  },
  {
    path: '/discovered/conditionalaccess',
    element: <ConditionalaccessDiscoveredView />
  },
  {
    path: '/discovered/databaseschema',
    element: <DatabaseschemaDiscoveredView />
  },
  {
    path: '/discovered/dataclassification',
    element: <DataclassificationDiscoveredView />
  },
  {
    path: '/discovered/dnsdhcp',
    element: <DnsdhcpDiscoveredView />
  },
  {
    path: '/discovered/entraidapp',
    element: <EntraidappDiscoveredView />
  },
  {
    path: '/discovered/environmentdetection',
    element: <EnvironmentdetectionDiscoveredView />
  },
  {
    path: '/discovered/exchange',
    element: <ExchangeDiscoveredView />
  },
  {
    path: '/discovered/externalidentity',
    element: <ExternalidentityDiscoveredView />
  },
  {
    path: '/discovered/fileserver',
    element: <FileserverDiscoveredView />
  },
  {
    path: '/discovered/filesystem',
    element: <FilesystemDiscoveredView />
  },
  {
    path: '/discovered/gcp',
    element: <GcpDiscoveredView />
  },
  {
    path: '/discovered/gpo',
    element: <GpoDiscoveredView />
  },
  {
    path: '/discovered/graph',
    element: <GraphDiscoveredView />
  },
  {
    path: '/discovered/infrastructure',
    element: <InfrastructureDiscoveredView />
  },
  {
    path: '/discovered/intune',
    element: <IntuneDiscoveredView />
  },
  {
    path: '/discovered/licensing',
    element: <LicensingDiscoveredView />
  },
  {
    path: '/discovered/multidomainforest',
    element: <MultidomainforestDiscoveredView />
  },
  {
    path: '/discovered/networkinfrastructure',
    element: <NetworkinfrastructureDiscoveredView />
  },
  {
    path: '/discovered/onedrive',
    element: <OnedriveDiscoveredView />
  },
  {
    path: '/discovered/paloalto',
    element: <PaloaltoDiscoveredView />
  },
  {
    path: '/discovered/physicalserver',
    element: <PhysicalserverDiscoveredView />
  },
  {
    path: '/discovered/powerbi',
    element: <PowerbiDiscoveredView />
  },
  {
    path: '/discovered/powerplatform',
    element: <PowerplatformDiscoveredView />
  },
  {
    path: '/discovered/printers',
    element: <PrintersDiscoveredView />
  },
  {
    path: '/discovered/scheduledtasks',
    element: <ScheduledtasksDiscoveredView />
  },
  {
    path: '/discovered/securityinfrastructure',
    element: <SecurityinfrastructureDiscoveredView />
  },
  {
    path: '/discovered/sharepoint',
    element: <SharepointDiscoveredView />
  },
  {
    path: '/discovered/sqlserver',
    element: <SqlserverDiscoveredView />
  },
  {
    path: '/discovered/storagearray',
    element: <StoragearrayDiscoveredView />
  },
  {
    path: '/discovered/teams',
    element: <TeamsDiscoveredView />
  },
  {
    path: '/discovered/virtualization',
    element: <VirtualizationDiscoveredView />
  },
  {
    path: '/discovered/vmware',
    element: <VmwareDiscoveredView />
  },
  {
    path: '/discovered/webserverconfig',
    element: <WebserverconfigDiscoveredView />
  },
  {
    path: '/discovered/hyperv',
    element: <HypervDiscoveredView />
  },
];
