// Auto-generated discovered view routes
// Generated by: scripts/generate-discovery-views.js
// Do not edit manually - regenerate using: npm run generate:views

import React, { lazy, Suspense } from 'react';
import { Spinner } from '../../components/atoms/Spinner';

// Loading fallback component for discovered views
const LoadingFallback: React.FC = () => (
  <div className="flex items-center justify-center h-full min-h-[400px]">
    <Spinner size="lg" />
  </div>
);

// Helper to wrap lazy components with Suspense
const withSuspense = (Component: React.LazyExoticComponent<React.ComponentType<any>>) => (
  <Suspense fallback={<LoadingFallback />}>
    <Component />
  </Suspense>
);

const ActivedirectoryDiscoveredView = lazy(() => import('./ActivedirectoryDiscoveredView'));
const ApplicationsDiscoveredView = lazy(() => import('./ApplicationsDiscoveredView'));
const AwsDiscoveredView = lazy(() => import('./AWSDiscoveredView'));
const AzureDiscoveredView = lazy(() => import('./AzureDiscoveredView'));
const AzureresourceDiscoveredView = lazy(() => import('./AzureresourceDiscoveredView'));
const BackuprecoveryDiscoveredView = lazy(() => import('./BackuprecoveryDiscoveredView'));
const CertificateauthorityDiscoveredView = lazy(() => import('./CertificateauthorityDiscoveredView'));
const CertificatesDiscoveredView = lazy(() => import('./CertificatesDiscoveredView'));
const ConditionalaccessDiscoveredView = lazy(() => import('./ConditionalaccessDiscoveredView'));
const DatabaseschemaDiscoveredView = lazy(() => import('./DatabaseschemaDiscoveredView'));
const DataclassificationDiscoveredView = lazy(() => import('./DataclassificationDiscoveredView'));
const DlpDiscoveredView = lazy(() => import('./DlpDiscoveredView'));
const DnsdhcpDiscoveredView = lazy(() => import('./DnsdhcpDiscoveredView'));
const EntraidappDiscoveredView = lazy(() => import('./EntraidappDiscoveredView'));
const EnvironmentdetectionDiscoveredView = lazy(() => import('./EnvironmentdetectionDiscoveredView'));
const ExchangeDiscoveredView = lazy(() => import('./ExchangeDiscoveredView'));
const ExternalidentityDiscoveredView = lazy(() => import('./ExternalidentityDiscoveredView'));
const FileserverDiscoveredView = lazy(() => import('./FileserverDiscoveredView'));
const FilesystemDiscoveredView = lazy(() => import('./FilesystemDiscoveredView'));
const GcpDiscoveredView = lazy(() => import('./GCPDiscoveredView'));
const GpoDiscoveredView = lazy(() => import('./GpoDiscoveredView'));
const GraphDiscoveredView = lazy(() => import('./GraphDiscoveredView'));
const InfrastructureDiscoveredView = lazy(() => import('./InfrastructureDiscoveredView'));
const IntuneDiscoveredView = lazy(() => import('./IntuneDiscoveredView'));
const LicensingDiscoveredView = lazy(() => import('./LicensingDiscoveredView'));
const MultidomainforestDiscoveredView = lazy(() => import('./MultidomainforestDiscoveredView'));
const NetworkinfrastructureDiscoveredView = lazy(() => import('./NetworkinfrastructureDiscoveredView'));
const OnedriveDiscoveredView = lazy(() => import('./OnedriveDiscoveredView'));
const PaloaltoDiscoveredView = lazy(() => import('./PaloaltoDiscoveredView'));
const PanoramainterrogationDiscoveredView = lazy(() => import('./PanoramainterrogationDiscoveredView'));
const PhysicalserverDiscoveredView = lazy(() => import('./PhysicalserverDiscoveredView'));
const PowerbiDiscoveredView = lazy(() => import('./PowerbiDiscoveredView'));
const PowerplatformDiscoveredView = lazy(() => import('./PowerplatformDiscoveredView'));
const PrintersDiscoveredView = lazy(() => import('./PrintersDiscoveredView'));
const ScheduledtasksDiscoveredView = lazy(() => import('./ScheduledtasksDiscoveredView'));
const SecurityinfrastructureDiscoveredView = lazy(() => import('./SecurityinfrastructureDiscoveredView'));
const SharepointDiscoveredView = lazy(() => import('./SharepointDiscoveredView'));
const SqlserverDiscoveredView = lazy(() => import('./SqlserverDiscoveredView'));
const StoragearrayDiscoveredView = lazy(() => import('./StoragearrayDiscoveredView'));
const TeamsDiscoveredView = lazy(() => import('./TeamsDiscoveredView'));
const VirtualizationDiscoveredView = lazy(() => import('./VirtualizationDiscoveredView'));
const VmwareDiscoveredView = lazy(() => import('./VMwareDiscoveredView'));
const WebserverconfigDiscoveredView = lazy(() => import('./WebserverconfigDiscoveredView'));
const HypervDiscoveredView = lazy(() => import('./HyperVDiscoveredView'));

export const discoveredRoutes = [
  {
    path: '/discovered/activedirectory',
    element: withSuspense(ActivedirectoryDiscoveredView)
  },
  {
    path: '/discovered/applications',
    element: withSuspense(ApplicationsDiscoveredView)
  },
  {
    path: '/discovered/aws',
    element: withSuspense(AwsDiscoveredView)
  },
  {
    path: '/discovered/azure',
    element: withSuspense(AzureDiscoveredView)
  },
  {
    path: '/discovered/azureresource',
    element: withSuspense(AzureresourceDiscoveredView)
  },
  {
    path: '/discovered/backuprecovery',
    element: withSuspense(BackuprecoveryDiscoveredView)
  },
  {
    path: '/discovered/certificateauthority',
    element: withSuspense(CertificateauthorityDiscoveredView)
  },
  {
    path: '/discovered/certificates',
    element: withSuspense(CertificatesDiscoveredView)
  },
  {
    path: '/discovered/conditionalaccess',
    element: withSuspense(ConditionalaccessDiscoveredView)
  },
  {
    path: '/discovered/databaseschema',
    element: withSuspense(DatabaseschemaDiscoveredView)
  },
  {
    path: '/discovered/dataclassification',
    element: withSuspense(DataclassificationDiscoveredView)
  },
  {
    path: '/discovered/dlp',
    element: withSuspense(DlpDiscoveredView)
  },
  {
    path: '/discovered/dnsdhcp',
    element: withSuspense(DnsdhcpDiscoveredView)
  },
  {
    path: '/discovered/entraidapp',
    element: withSuspense(EntraidappDiscoveredView)
  },
  {
    path: '/discovered/environmentdetection',
    element: withSuspense(EnvironmentdetectionDiscoveredView)
  },
  {
    path: '/discovered/exchange',
    element: withSuspense(ExchangeDiscoveredView)
  },
  {
    path: '/discovered/externalidentity',
    element: withSuspense(ExternalidentityDiscoveredView)
  },
  {
    path: '/discovered/fileserver',
    element: withSuspense(FileserverDiscoveredView)
  },
  {
    path: '/discovered/filesystem',
    element: withSuspense(FilesystemDiscoveredView)
  },
  {
    path: '/discovered/gcp',
    element: withSuspense(GcpDiscoveredView)
  },
  {
    path: '/discovered/gpo',
    element: withSuspense(GpoDiscoveredView)
  },
  {
    path: '/discovered/graph',
    element: withSuspense(GraphDiscoveredView)
  },
  {
    path: '/discovered/infrastructure',
    element: withSuspense(InfrastructureDiscoveredView)
  },
  {
    path: '/discovered/intune',
    element: withSuspense(IntuneDiscoveredView)
  },
  {
    path: '/discovered/licensing',
    element: withSuspense(LicensingDiscoveredView)
  },
  {
    path: '/discovered/multidomainforest',
    element: withSuspense(MultidomainforestDiscoveredView)
  },
  {
    path: '/discovered/networkinfrastructure',
    element: withSuspense(NetworkinfrastructureDiscoveredView)
  },
  {
    path: '/discovered/onedrive',
    element: withSuspense(OnedriveDiscoveredView)
  },
  {
    path: '/discovered/paloalto',
    element: withSuspense(PaloaltoDiscoveredView)
  },
  {
    path: '/discovered/panoramainterrogation',
    element: withSuspense(PanoramainterrogationDiscoveredView)
  },
  {
    path: '/discovered/physicalserver',
    element: withSuspense(PhysicalserverDiscoveredView)
  },
  {
    path: '/discovered/powerbi',
    element: withSuspense(PowerbiDiscoveredView)
  },
  {
    path: '/discovered/powerplatform',
    element: withSuspense(PowerplatformDiscoveredView)
  },
  {
    path: '/discovered/printers',
    element: withSuspense(PrintersDiscoveredView)
  },
  {
    path: '/discovered/scheduledtasks',
    element: withSuspense(ScheduledtasksDiscoveredView)
  },
  {
    path: '/discovered/securityinfrastructure',
    element: withSuspense(SecurityinfrastructureDiscoveredView)
  },
  {
    path: '/discovered/sharepoint',
    element: withSuspense(SharepointDiscoveredView)
  },
  {
    path: '/discovered/sqlserver',
    element: withSuspense(SqlserverDiscoveredView)
  },
  {
    path: '/discovered/storagearray',
    element: withSuspense(StoragearrayDiscoveredView)
  },
  {
    path: '/discovered/teams',
    element: withSuspense(TeamsDiscoveredView)
  },
  {
    path: '/discovered/virtualization',
    element: withSuspense(VirtualizationDiscoveredView)
  },
  {
    path: '/discovered/vmware',
    element: withSuspense(VmwareDiscoveredView)
  },
  {
    path: '/discovered/webserverconfig',
    element: withSuspense(WebserverconfigDiscoveredView)
  },
  {
    path: '/discovered/hyperv',
    element: withSuspense(HypervDiscoveredView)
  },
];
