// Auto-generated discovered view routes
// Generated by: scripts/generate-discovery-views.js
// Do not edit manually - regenerate using: npm run generate:views

import React, { lazy } from 'react';

// CRITICAL: All imports use RELATIVE paths (same directory)
const ActivedirectoryDiscoveredView = lazy(() => import('./ActivedirectoryDiscoveredView'));
const ApplicationsDiscoveredView = lazy(() => import('./ApplicationsDiscoveredView'));
const AWSDiscoveredView = lazy(() => import('./AWSDiscoveredView'));
const AzureDiscoveredView = lazy(() => import('./AzureDiscoveredView'));
const AzureresourceDiscoveredView = lazy(() => import('./AzureresourceDiscoveredView'));
const BackuprecoveryDiscoveredView = lazy(() => import('./BackuprecoveryDiscoveredView'));
const CertificateauthorityDiscoveredView = lazy(() => import('./CertificateauthorityDiscoveredView'));
const CertificatesDiscoveredView = lazy(() => import('./CertificatesDiscoveredView'));
const ConditionalaccessDiscoveredView = lazy(() => import('./ConditionalaccessDiscoveredView'));
const DatabaseschemaDiscoveredView = lazy(() => import('./DatabaseschemaDiscoveredView'));
const DataclassificationDiscoveredView = lazy(() => import('./DataclassificationDiscoveredView'));
const DnsdhcpDiscoveredView = lazy(() => import('./DnsdhcpDiscoveredView'));
const EntraidappDiscoveredView = lazy(() => import('./EntraidappDiscoveredView'));
const EnvironmentdetectionDiscoveredView = lazy(() => import('./EnvironmentdetectionDiscoveredView'));
const ExchangeDiscoveredView = lazy(() => import('./ExchangeDiscoveredView'));
const ExternalidentityDiscoveredView = lazy(() => import('./ExternalidentityDiscoveredView'));
const FileserverDiscoveredView = lazy(() => import('./FileserverDiscoveredView'));
const FilesystemDiscoveredView = lazy(() => import('./FilesystemDiscoveredView'));
const GCPDiscoveredView = lazy(() => import('./GCPDiscoveredView'));
const GpoDiscoveredView = lazy(() => import('./GpoDiscoveredView'));
const GraphDiscoveredView = lazy(() => import('./GraphDiscoveredView'));
const HyperVDiscoveredView = lazy(() => import('./HyperVDiscoveredView'));
const InfrastructureDiscoveredView = lazy(() => import('./InfrastructureDiscoveredView'));
const IntuneDiscoveredView = lazy(() => import('./IntuneDiscoveredView'));
const LicensingDiscoveredView = lazy(() => import('./LicensingDiscoveredView'));
const MultidomainforestDiscoveredView = lazy(() => import('./MultidomainforestDiscoveredView'));
const NetworkinfrastructureDiscoveredView = lazy(() => import('./NetworkinfrastructureDiscoveredView'));
const OnedriveDiscoveredView = lazy(() => import('./OnedriveDiscoveredView'));
const PaloaltoDiscoveredView = lazy(() => import('./PaloaltoDiscoveredView'));
const PhysicalserverDiscoveredView = lazy(() => import('./PhysicalserverDiscoveredView'));
const PowerbiDiscoveredView = lazy(() => import('./PowerbiDiscoveredView'));
const PowerplatformDiscoveredView = lazy(() => import('./PowerplatformDiscoveredView'));
const PrintersDiscoveredView = lazy(() => import('./PrintersDiscoveredView'));
const ScheduledtasksDiscoveredView = lazy(() => import('./ScheduledtasksDiscoveredView'));
const SecurityinfrastructureDiscoveredView = lazy(() => import('./SecurityinfrastructureDiscoveredView'));
const SharepointDiscoveredView = lazy(() => import('./SharepointDiscoveredView'));
const SqlserverDiscoveredView = lazy(() => import('./SqlserverDiscoveredView'));
const StoragearrayDiscoveredView = lazy(() => import('./StoragearrayDiscoveredView'));
const TeamsDiscoveredView = lazy(() => import('./TeamsDiscoveredView'));
const VirtualizationDiscoveredView = lazy(() => import('./VirtualizationDiscoveredView'));
const VMwareDiscoveredView = lazy(() => import('./VMwareDiscoveredView'));
const WebserverconfigDiscoveredView = lazy(() => import('./WebserverconfigDiscoveredView'));

export const discoveredRoutes = [
  { path: '/discovery/discovered/activedirectory', element: React.createElement(ActivedirectoryDiscoveredView) },
  { path: '/discovery/discovered/applications', element: React.createElement(ApplicationsDiscoveredView) },
  { path: '/discovery/discovered/aws', element: React.createElement(AWSDiscoveredView) },
  { path: '/discovery/discovered/azure', element: React.createElement(AzureDiscoveredView) },
  { path: '/discovery/discovered/azureresource', element: React.createElement(AzureresourceDiscoveredView) },
  { path: '/discovery/discovered/backuprecovery', element: React.createElement(BackuprecoveryDiscoveredView) },
  { path: '/discovery/discovered/certificateauthority', element: React.createElement(CertificateauthorityDiscoveredView) },
  { path: '/discovery/discovered/certificates', element: React.createElement(CertificatesDiscoveredView) },
  { path: '/discovery/discovered/conditionalaccess', element: React.createElement(ConditionalaccessDiscoveredView) },
  { path: '/discovery/discovered/databaseschema', element: React.createElement(DatabaseschemaDiscoveredView) },
  { path: '/discovery/discovered/dataclassification', element: React.createElement(DataclassificationDiscoveredView) },
  { path: '/discovery/discovered/dnsdhcp', element: React.createElement(DnsdhcpDiscoveredView) },
  { path: '/discovery/discovered/entraidapp', element: React.createElement(EntraidappDiscoveredView) },
  { path: '/discovery/discovered/environmentdetection', element: React.createElement(EnvironmentdetectionDiscoveredView) },
  { path: '/discovery/discovered/exchange', element: React.createElement(ExchangeDiscoveredView) },
  { path: '/discovery/discovered/externalidentity', element: React.createElement(ExternalidentityDiscoveredView) },
  { path: '/discovery/discovered/fileserver', element: React.createElement(FileserverDiscoveredView) },
  { path: '/discovery/discovered/filesystem', element: React.createElement(FilesystemDiscoveredView) },
  { path: '/discovery/discovered/gcp', element: React.createElement(GCPDiscoveredView) },
  { path: '/discovery/discovered/gpo', element: React.createElement(GpoDiscoveredView) },
  { path: '/discovery/discovered/graph', element: React.createElement(GraphDiscoveredView) },
  { path: '/discovery/discovered/hyperv', element: React.createElement(HyperVDiscoveredView) },
  { path: '/discovery/discovered/infrastructure', element: React.createElement(InfrastructureDiscoveredView) },
  { path: '/discovery/discovered/intune', element: React.createElement(IntuneDiscoveredView) },
  { path: '/discovery/discovered/licensing', element: React.createElement(LicensingDiscoveredView) },
  { path: '/discovery/discovered/multidomainforest', element: React.createElement(MultidomainforestDiscoveredView) },
  { path: '/discovery/discovered/networkinfrastructure', element: React.createElement(NetworkinfrastructureDiscoveredView) },
  { path: '/discovery/discovered/onedrive', element: React.createElement(OnedriveDiscoveredView) },
  { path: '/discovery/discovered/paloalto', element: React.createElement(PaloaltoDiscoveredView) },
  { path: '/discovery/discovered/physicalserver', element: React.createElement(PhysicalserverDiscoveredView) },
  { path: '/discovery/discovered/powerbi', element: React.createElement(PowerbiDiscoveredView) },
  { path: '/discovery/discovered/powerplatform', element: React.createElement(PowerplatformDiscoveredView) },
  { path: '/discovery/discovered/printers', element: React.createElement(PrintersDiscoveredView) },
  { path: '/discovery/discovered/scheduledtasks', element: React.createElement(ScheduledtasksDiscoveredView) },
  { path: '/discovery/discovered/securityinfrastructure', element: React.createElement(SecurityinfrastructureDiscoveredView) },
  { path: '/discovery/discovered/sharepoint', element: React.createElement(SharepointDiscoveredView) },
  { path: '/discovery/discovered/sqlserver', element: React.createElement(SqlserverDiscoveredView) },
  { path: '/discovery/discovered/storagearray', element: React.createElement(StoragearrayDiscoveredView) },
  { path: '/discovery/discovered/teams', element: React.createElement(TeamsDiscoveredView) },
  { path: '/discovery/discovered/virtualization', element: React.createElement(VirtualizationDiscoveredView) },
  { path: '/discovery/discovered/vmware', element: React.createElement(VMwareDiscoveredView) },
  { path: '/discovery/discovered/webserverconfig', element: React.createElement(WebserverconfigDiscoveredView) },
];
