// Auto-generated sidebar navigation items for discovered views
// Generated by: scripts/generate-discovery-views.js

import React from 'react';
import {
  Database, Package, Cloud, Layers, HardDrive, Shield, Key, Lock,
  Tag, Network, AppWindow, Radar, Mail, Users, Server, FileText,
  Cpu, GitBranch, Folder, Folders, BarChart3, Workflow, Printer, Calendar,
  MessageSquare, Globe, Smartphone
} from 'lucide-react';

export const discoveredNavItems = [
  // Identity & Access
  { path: '/discovered/activedirectory', label: 'Active Directory', icon: React.createElement(Database, { size: 16 }) },
  { path: '/discovered/entraidapp', label: 'Entra ID Applications', icon: React.createElement(AppWindow, { size: 16 }) },
  { path: '/discovered/externalidentity', label: 'External Identities', icon: React.createElement(Users, { size: 16 }) },
  { path: '/discovered/graph', label: 'Microsoft Graph', icon: React.createElement(Network, { size: 16 }) },
  { path: '/discovered/multidomainforest', label: 'Multi-Domain Forest', icon: React.createElement(GitBranch, { size: 16 }) },

  // Infrastructure
  { path: '/discovered/applications', label: 'Applications', icon: React.createElement(Package, { size: 16 }) },
  { path: '/discovered/backuprecovery', label: 'Backup & Recovery', icon: React.createElement(HardDrive, { size: 16 }) },
  { path: '/discovered/environmentdetection', label: 'Environment Detection', icon: React.createElement(Radar, { size: 16 }) },
  { path: '/discovered/fileserver', label: 'File Servers', icon: React.createElement(Server, { size: 16 }) },
  { path: '/discovered/filesystem', label: 'File Systems', icon: React.createElement(HardDrive, { size: 16 }) },
  { path: '/discovered/gpo', label: 'Group Policies', icon: React.createElement(FileText, { size: 16 }) },
  { path: '/discovered/infrastructure', label: 'Infrastructure', icon: React.createElement(Server, { size: 16 }) },
  { path: '/discovered/intune', label: 'Intune', icon: React.createElement(Smartphone, { size: 16 }) },
  { path: '/discovered/licensing', label: 'Licensing', icon: React.createElement(FileText, { size: 16 }) },
  { path: '/discovered/physicalserver', label: 'Physical Servers', icon: React.createElement(Server, { size: 16 }) },
  { path: '/discovered/printers', label: 'Printers', icon: React.createElement(Printer, { size: 16 }) },
  { path: '/discovered/scheduledtasks', label: 'Scheduled Tasks', icon: React.createElement(Calendar, { size: 16 }) },
  { path: '/discovered/storagearray', label: 'Storage Arrays', icon: React.createElement(HardDrive, { size: 16 }) },
  { path: '/discovered/virtualization', label: 'Virtualization', icon: React.createElement(Cpu, { size: 16 }) },
  { path: '/discovered/vmware', label: 'VMware', icon: React.createElement(Cpu, { size: 16 }) },
  { path: '/discovered/webserverconfig', label: 'Web Server Config', icon: React.createElement(Globe, { size: 16 }) },
  { path: '/discovered/hyperv', label: 'Hyper-V', icon: React.createElement(Cpu, { size: 16 }) },

  // Cloud Services
  { path: '/discovered/aws', label: 'AWS Resources', icon: React.createElement(Cloud, { size: 16 }) },
  { path: '/discovered/azure', label: 'Azure Resources', icon: React.createElement(Cloud, { size: 16 }) },
  { path: '/discovered/azureresource', label: 'Azure Resource Manager', icon: React.createElement(Layers, { size: 16 }) },
  { path: '/discovered/gcp', label: 'GCP Resources', icon: React.createElement(Cloud, { size: 16 }) },

  // Collaboration
  { path: '/discovered/exchange', label: 'Exchange', icon: React.createElement(Mail, { size: 16 }) },
  { path: '/discovered/onedrive', label: 'OneDrive', icon: React.createElement(Folders, { size: 16 }) },
  { path: '/discovered/powerplatform', label: 'Power Platform', icon: React.createElement(Workflow, { size: 16 }) },
  { path: '/discovered/sharepoint', label: 'SharePoint', icon: React.createElement(Folder, { size: 16 }) },
  { path: '/discovered/teams', label: 'Microsoft Teams', icon: React.createElement(MessageSquare, { size: 16 }) },

  // Security
  { path: '/discovered/certificateauthority', label: 'Certificate Authority', icon: React.createElement(Shield, { size: 16 }) },
  { path: '/discovered/certificates', label: 'Certificates', icon: React.createElement(Key, { size: 16 }) },
  { path: '/discovered/conditionalaccess', label: 'Conditional Access', icon: React.createElement(Lock, { size: 16 }) },
  { path: '/discovered/paloalto', label: 'Palo Alto Networks', icon: React.createElement(Shield, { size: 16 }) },
  { path: '/discovered/securityinfrastructure', label: 'Security Infrastructure', icon: React.createElement(Shield, { size: 16 }) },

  // Network
  { path: '/discovered/dnsdhcp', label: 'DNS & DHCP', icon: React.createElement(Network, { size: 16 }) },
  { path: '/discovered/networkinfrastructure', label: 'Network Infrastructure', icon: React.createElement(Network, { size: 16 }) },

  // Data & Databases
  { path: '/discovered/databaseschema', label: 'Database Schemas', icon: React.createElement(Database, { size: 16 }) },
  { path: '/discovered/dataclassification', label: 'Data Classification', icon: React.createElement(Tag, { size: 16 }) },
  { path: '/discovered/powerbi', label: 'Power BI', icon: React.createElement(BarChart3, { size: 16 }) },
  { path: '/discovered/sqlserver', label: 'SQL Server', icon: React.createElement(Database, { size: 16 }) }
];
