// Auto-generated sidebar navigation items for discovered views
// Sorted alphabetically by label

import {
  Database, Package, Cloud, Layers, HardDrive, Shield, Key, Lock,
  Tag, Network, AppWindow, Radar, Mail, Users, Server, FileText,
  Cpu, GitBranch, Folders, BarChart3, Workflow, Printer, Calendar,
  MessageSquare, Globe, Smartphone, Folder
} from 'lucide-react';

export const discoveredNavItems = [
  { path: '/discovered/activedirectory', label: 'Active Directory', icon: <Database size={16} /> },
  { path: '/discovered/applications', label: 'Applications', icon: <Package size={16} /> },
  { path: '/discovered/aws', label: 'AWS Resources', icon: <Cloud size={16} /> },
  { path: '/discovered/azureresource', label: 'Azure Infrastructure', icon: <Layers size={16} /> },
  { path: '/discovered/backuprecovery', label: 'Backup & Recovery', icon: <HardDrive size={16} /> },
  { path: '/discovered/certificateauthority', label: 'Certificate Authority', icon: <Shield size={16} /> },
  { path: '/discovered/certificates', label: 'Certificates', icon: <Key size={16} /> },
  { path: '/discovered/conditionalaccess', label: 'Conditional Access', icon: <Lock size={16} /> },
  { path: '/discovered/dataclassification', label: 'Data Classification', icon: <Tag size={16} /> },
  { path: '/discovered/dlp', label: 'Data Loss Prevention', icon: <Shield size={16} /> },
  { path: '/discovered/databaseschema', label: 'Database Schemas', icon: <Database size={16} /> },
  { path: '/discovered/dnsdhcp', label: 'DNS & DHCP', icon: <Network size={16} /> },
  { path: '/discovered/domain', label: 'Domain', icon: <Network size={16} /> },
  { path: '/discovered/azure', label: 'Entra ID & M365', icon: <Cloud size={16} /> },
  { path: '/discovered/entraidapp', label: 'Entra ID Applications', icon: <AppWindow size={16} /> },
  { path: '/discovered/environmentdetection', label: 'Environment Detection', icon: <Radar size={16} /> },
  { path: '/discovered/exchange', label: 'Exchange', icon: <Mail size={16} /> },
  { path: '/discovered/externalidentity', label: 'External Identities', icon: <Users size={16} /> },
  { path: '/discovered/fileserver', label: 'File Servers', icon: <Server size={16} /> },
  { path: '/discovered/filesystem', label: 'File Systems', icon: <HardDrive size={16} /> },
  { path: '/discovered/gcp', label: 'GCP Resources', icon: <Cloud size={16} /> },
  { path: '/discovered/googleworkspace', label: 'Google Workspace', icon: <Cloud size={16} /> },
  { path: '/discovered/gpo', label: 'Group Policies', icon: <FileText size={16} /> },
  { path: '/discovered/hyperv', label: 'Hyper-V', icon: <Cpu size={16} /> },
  { path: '/discovered/infrastructure', label: 'Infrastructure', icon: <Server size={16} /> },
  { path: '/discovered/intune', label: 'Intune', icon: <Smartphone size={16} /> },
  { path: '/discovered/licensing', label: 'Licensing', icon: <FileText size={16} /> },
  { path: '/discovered/graph', label: 'Microsoft Graph', icon: <Network size={16} /> },
  { path: '/discovered/teams', label: 'Microsoft Teams', icon: <MessageSquare size={16} /> },
  { path: '/discovered/multidomainforest', label: 'Multi-Domain Forest', icon: <GitBranch size={16} /> },
  { path: '/discovered/networkinfrastructure', label: 'Network Infrastructure', icon: <Network size={16} /> },
  { path: '/discovered/onedrive', label: 'OneDrive', icon: <Folders size={16} /> },
  { path: '/discovered/office365', label: 'Office 365', icon: <Package size={16} /> },
  { path: '/discovered/paloalto', label: 'Palo Alto Networks', icon: <Shield size={16} /> },
  { path: '/discovered/panoramainterrogation', label: 'Panorama Interrogation', icon: <Shield size={16} /> },
  { path: '/discovered/physicalserver', label: 'Physical Servers', icon: <Server size={16} /> },
  { path: '/discovered/powerbi', label: 'Power BI', icon: <BarChart3 size={16} /> },
  { path: '/discovered/powerplatform', label: 'Power Platform', icon: <Workflow size={16} /> },
  { path: '/discovered/printers', label: 'Printers', icon: <Printer size={16} /> },
  { path: '/discovered/scheduledtasks', label: 'Scheduled Tasks', icon: <Calendar size={16} /> },
  { path: '/discovered/securityinfrastructure', label: 'Security Infrastructure', icon: <Shield size={16} /> },
  { path: '/discovered/sharepoint', label: 'SharePoint', icon: <Folder size={16} /> },
  { path: '/discovered/sqlserver', label: 'SQL Server', icon: <Database size={16} /> },
  { path: '/discovered/storagearray', label: 'Storage Arrays', icon: <HardDrive size={16} /> },
  { path: '/discovered/virtualization', label: 'Virtualization', icon: <Cpu size={16} /> },
  { path: '/discovered/vmware', label: 'VMware', icon: <Cpu size={16} /> },
  { path: '/discovered/webserverconfig', label: 'Web Server Config', icon: <Globe size={16} /> },
];
