// Auto-generated sidebar navigation items for discovered views
// Generated by: scripts/generate-discovery-views.js

import {
  Database, Package, Cloud, Layers, HardDrive, Shield, Key, Lock,
  Tag, Network, AppWindow, Radar, Mail, Users, Server, FileText,
  Cpu, GitBranch, Folders, BarChart3, Workflow, Printer, Calendar,
  MessageSquare, Globe, Smartphone, Folder
} from 'lucide-react';

export const discoveredNavItems = [
  // Identity & Access
  { path: '/discovery/discovered/activedirectory', label: 'Active Directory', icon: <Database size={16} /> },
  { path: '/discovery/discovered/entraidapp', label: 'Entra ID Applications', icon: <AppWindow size={16} /> },
  { path: '/discovery/discovered/externalidentity', label: 'External Identities', icon: <Users size={16} /> },
  { path: '/discovery/discovered/graph', label: 'Microsoft Graph', icon: <Network size={16} /> },
  { path: '/discovery/discovered/multidomainforest', label: 'Multi-Domain Forest', icon: <GitBranch size={16} /> },

  // Infrastructure
  { path: '/discovery/discovered/applications', label: 'Applications', icon: <Package size={16} /> },
  { path: '/discovery/discovered/backuprecovery', label: 'Backup & Recovery', icon: <HardDrive size={16} /> },
  { path: '/discovery/discovered/environmentdetection', label: 'Environment Detection', icon: <Radar size={16} /> },
  { path: '/discovery/discovered/fileserver', label: 'File Servers', icon: <Server size={16} /> },
  { path: '/discovery/discovered/filesystem', label: 'File Systems', icon: <HardDrive size={16} /> },
  { path: '/discovery/discovered/gpo', label: 'Group Policies', icon: <FileText size={16} /> },
  { path: '/discovery/discovered/infrastructure', label: 'Infrastructure', icon: <Server size={16} /> },
  { path: '/discovery/discovered/intune', label: 'Intune', icon: <Smartphone size={16} /> },
  { path: '/discovery/discovered/licensing', label: 'Licensing', icon: <FileText size={16} /> },
  { path: '/discovery/discovered/physicalserver', label: 'Physical Servers', icon: <Server size={16} /> },
  { path: '/discovery/discovered/printers', label: 'Printers', icon: <Printer size={16} /> },
  { path: '/discovery/discovered/scheduledtasks', label: 'Scheduled Tasks', icon: <Calendar size={16} /> },
  { path: '/discovery/discovered/storagearray', label: 'Storage Arrays', icon: <HardDrive size={16} /> },
  { path: '/discovery/discovered/virtualization', label: 'Virtualization', icon: <Cpu size={16} /> },
  { path: '/discovery/discovered/vmware', label: 'VMware', icon: <Cpu size={16} /> },
  { path: '/discovery/discovered/webserverconfig', label: 'Web Server Config', icon: <Globe size={16} /> },
  { path: '/discovery/discovered/hyperv', label: 'Hyper-V', icon: <Cpu size={16} /> },

  // Cloud Services
  { path: '/discovery/discovered/aws', label: 'AWS Resources', icon: <Cloud size={16} /> },
  { path: '/discovery/discovered/azure', label: 'Azure Resources', icon: <Cloud size={16} /> },
  { path: '/discovery/discovered/azureresource', label: 'Azure Resource Manager', icon: <Layers size={16} /> },
  { path: '/discovery/discovered/gcp', label: 'GCP Resources', icon: <Cloud size={16} /> },

  // Collaboration
  { path: '/discovery/discovered/exchange', label: 'Exchange', icon: <Mail size={16} /> },
  { path: '/discovery/discovered/onedrive', label: 'OneDrive', icon: <Folders size={16} /> },
  { path: '/discovery/discovered/powerplatform', label: 'Power Platform', icon: <Workflow size={16} /> },
  { path: '/discovery/discovered/sharepoint', label: 'SharePoint', icon: <Folder size={16} /> },
  { path: '/discovery/discovered/teams', label: 'Microsoft Teams', icon: <MessageSquare size={16} /> },

  // Security
  { path: '/discovery/discovered/certificateauthority', label: 'Certificate Authority', icon: <Shield size={16} /> },
  { path: '/discovery/discovered/certificates', label: 'Certificates', icon: <Key size={16} /> },
  { path: '/discovery/discovered/conditionalaccess', label: 'Conditional Access', icon: <Lock size={16} /> },
  { path: '/discovery/discovered/dlp', label: 'Data Loss Prevention', icon: <Shield size={16} /> },
  { path: '/discovery/discovered/paloalto', label: 'Palo Alto Networks', icon: <Shield size={16} /> },
  { path: '/discovery/discovered/panoramainterrogation', label: 'Panorama Interrogation', icon: <Shield size={16} /> },
  { path: '/discovery/discovered/securityinfrastructure', label: 'Security Infrastructure', icon: <Shield size={16} /> },

  // Network
  { path: '/discovery/discovered/dnsdhcp', label: 'DNS & DHCP', icon: <Network size={16} /> },
  { path: '/discovery/discovered/networkinfrastructure', label: 'Network Infrastructure', icon: <Network size={16} /> },

  // Data & Databases
  { path: '/discovery/discovered/databaseschema', label: 'Database Schemas', icon: <Database size={16} /> },
  { path: '/discovery/discovered/dataclassification', label: 'Data Classification', icon: <Tag size={16} /> },
  { path: '/discovery/discovered/powerbi', label: 'Power BI', icon: <BarChart3 size={16} /> },
  { path: '/discovery/discovered/sqlserver', label: 'SQL Server', icon: <Database size={16} /> }
];
