/**
 * Active Directory Discovered View
 *
 * Auto-generated discovered data view for Active Directory.
 * Displays CSV data from: AzureDiscovery_Users.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module activedirectory
 * @category identity
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Active Directory discovered data view component
 */
export const ActivedirectoryDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Active Directory"
      csvPath="AzureDiscovery_Users.csv"
      title="Active Directory"
      description="Active Directory objects, OUs, and domain configuration"
      enableSearch={true}
      enableExport={true}
      data-cy="activedirectory-discovered-view"
    />
  );
};

export default ActivedirectoryDiscoveredView;
