/**
 * Applications Discovered View
 *
 * Auto-generated discovered data view for Applications.
 * Displays CSV data from: ApplicationsDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module applications
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Applications discovered data view component
 */
export const ApplicationsDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Applications"
      csvPath="ApplicationsDiscovery.csv"
      title="Applications"
      description="Installed applications and software inventory"
      enableSearch={true}
      enableExport={true}
      data-cy="applications-discovered-view"
    />
  );
};

export default ApplicationsDiscoveredView;
