/**
 * AWS Resources Discovered View
 *
 * Auto-generated discovered data view for AWS Resources.
 * Displays CSV data from: AWSDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module aws
 * @category cloud
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * AWS Resources discovered data view component
 */
export const AwsDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="AWS Resources"
      csvPath="AWSDiscovery.csv"
      title="AWS Resources"
      description="Amazon Web Services cloud resources and configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="aws-discovered-view"
    />
  );
};

export default AwsDiscoveredView;


