/**
 * Azure Resources Discovered View
 *
 * Auto-generated discovered data view for Azure Resources.
 * Displays CSV data from: azure/results.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module azure
 * @category cloud
 */

import React, { useState, useCallback } from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';
import { useCsvDataLoader } from '../../hooks/useCsvDataLoader';

/**
 * Azure Resources discovered data view component
 */
export const AzureDiscoveredView: React.FC = () => {
  const [searchText, setSearchText] = useState('');

  const {
    data,
    columns,
    loading,
    error,
    lastRefresh,
    reload,
  } = useCsvDataLoader('azure/results.csv');

  const handleRefresh = useCallback(() => {
    reload();
  }, [reload]);

  const handleExport = useCallback(() => {
    // Export functionality handled by VirtualizedDataGrid
    console.log('[AzureDiscoveredView] Export requested');
  }, []);

  return (
    <DiscoveredViewTemplate
      title="Azure Resources"
      description="Microsoft Azure cloud resources and services"
      data={data}
      columns={columns}
      loading={loading}
      error={error}
      searchText={searchText}
      onSearchChange={setSearchText}
      onRefresh={handleRefresh}
      onExport={handleExport}
      lastRefresh={lastRefresh}
      enableSearch={true}
      enableExport={true}
      data-cy="azure-discovered-view"
    />
  );
};

export default AzureDiscoveredView;
