/**
 * Azure Resources Discovered View
 *
 * Auto-generated discovered data view for Azure Resources.
 * Displays CSV data from: AzureDiscovery_Tenant.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module azure
 * @category cloud
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Azure Resources discovered data view component
 */
export const AzureDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Azure Resources"
      csvPath="AzureDiscovery_Tenant.csv"
      title="Azure Resources"
      description="Microsoft Azure cloud resources and services"
      enableSearch={true}
      enableExport={true}
      data-cy="azure-discovered-view"
    />
  );
};

export default AzureDiscoveredView;
