/**
 * Azure Resource Manager Discovered View
 *
 * Auto-generated discovered data view for Azure Resource Manager.
 * Displays CSV data from: AzureResourceDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module azureresource
 * @category cloud
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Azure Resource Manager discovered data view component
 */
export const AzureresourceDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Azure Resource Manager"
      csvPath="AzureResourceDiscovery.csv"
      title="Azure Resource Manager"
      description="Azure ARM resources, subscriptions, and resource groups"
      enableSearch={true}
      enableExport={true}
      data-cy="azureresource-discovered-view"
    />
  );
};

export default AzureresourceDiscoveredView;
