/**
 * Backup & Recovery Discovered View
 *
 * Auto-generated discovered data view for Backup & Recovery.
 * Displays CSV data from: BackupRecoveryDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module backuprecovery
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Backup & Recovery discovered data view component
 */
export const BackuprecoveryDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Backup & Recovery"
      csvPath="BackupRecoveryDiscovery.csv"
      title="Backup & Recovery"
      description="Backup systems, recovery points, and disaster recovery configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="backuprecovery-discovered-view"
    />
  );
};

export default BackuprecoveryDiscoveredView;
