/**
 * Certificate Authority Discovered View
 *
 * Auto-generated discovered data view for Certificate Authority.
 * Displays CSV data from: CertificateAuthorityDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module certificateauthority
 * @category security
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Certificate Authority discovered data view component
 */
export const CertificateauthorityDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Certificate Authority"
      csvPath="CertificateAuthorityDiscovery.csv"
      title="Certificate Authority"
      description="PKI certificate authorities and certificate services"
      enableSearch={true}
      enableExport={true}
      data-cy="certificateauthority-discovered-view"
    />
  );
};

export default CertificateauthorityDiscoveredView;
