/**
 * Conditional Access Discovered View
 *
 * Auto-generated discovered data view for Conditional Access.
 * Displays CSV data from: ConditionalAccessDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module conditionalaccess
 * @category security
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Conditional Access discovered data view component
 */
export const ConditionalaccessDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Conditional Access"
      csvPath="ConditionalAccessDiscovery.csv"
      title="Conditional Access"
      description="Azure AD conditional access policies and rules"
      enableSearch={true}
      enableExport={true}
      data-cy="conditionalaccess-discovered-view"
    />
  );
};

export default ConditionalaccessDiscoveredView;


