/**
 * Database Schemas Discovered View
 *
 * Auto-generated discovered data view for Database Schemas.
 * Displays CSV data from: DatabaseSchemaDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module databaseschema
 * @category data
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Database Schemas discovered data view component
 */
export const DatabaseschemaDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Database Schemas"
      csvPath="DatabaseSchemaDiscovery.csv"
      title="Database Schemas"
      description="Database structures, tables, and schema definitions"
      enableSearch={true}
      enableExport={true}
      data-cy="databaseschema-discovered-view"
    />
  );
};

export default DatabaseschemaDiscoveredView;
