/**
 * Data Classification Discovered View
 *
 * Auto-generated discovered data view for Data Classification.
 * Displays CSV data from: DataClassificationDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module dataclassification
 * @category data
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Data Classification discovered data view component
 */
export const DataclassificationDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Data Classification"
      csvPath="DataClassificationDiscovery.csv"
      title="Data Classification"
      description="Data sensitivity labels and classification tags"
      enableSearch={true}
      enableExport={true}
      data-cy="dataclassification-discovered-view"
    />
  );
};

export default DataclassificationDiscoveredView;
