/**
 * DLP (Data Loss Prevention) Discovered View
 *
 * Auto-generated discovered data view for DLP.
 * Displays CSV data from: DLPDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module dlp
 * @category security
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * DLP discovered data view component
 */
export const DlpDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="DLP"
      csvPath="DLPDiscovery.csv"
      title="Data Loss Prevention"
      description="DLP policies, rules, and sensitive information types"
      enableSearch={true}
      enableExport={true}
      data-cy="dlp-discovered-view"
    />
  );
};

export default DlpDiscoveredView;
