/**
 * DNS & DHCP Discovered View
 *
 * Auto-generated discovered data view for DNS & DHCP.
 * Displays CSV data from: DNSDHCPDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module dnsdhcp
 * @category network
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * DNS & DHCP discovered data view component
 */
export const DnsdhcpDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="DNS & DHCP"
      csvPath="DNSDHCPDiscovery.csv"
      title="DNS & DHCP"
      description="DNS zones, DHCP scopes, and network services"
      enableSearch={true}
      enableExport={true}
      data-cy="dnsdhcp-discovered-view"
    />
  );
};

export default DnsdhcpDiscoveredView;
