/**
 * Entra ID Applications Discovered View
 *
 * Auto-generated discovered data view for Entra ID Applications.
 * Displays CSV data from: EntraIDAppDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module entraidapp
 * @category identity
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Entra ID Applications discovered data view component
 */
export const EntraidappDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Entra ID Applications"
      csvPath="EntraIDAppDiscovery.csv"
      title="Entra ID Applications"
      description="Azure AD application registrations and service principals"
      enableSearch={true}
      enableExport={true}
      data-cy="entraidapp-discovered-view"
    />
  );
};

export default EntraidappDiscoveredView;
