/**
 * Environment Detection Discovered View
 *
 * Auto-generated discovered data view for Environment Detection.
 * Displays CSV data from: EnvironmentDetection_OperatingSystem.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module environmentdetection
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Environment Detection discovered data view component
 */
export const EnvironmentdetectionDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Environment Detection"
      csvPath="EnvironmentDetection_OperatingSystem.csv"
      title="Environment Detection"
      description="Automatic environment discovery and topology detection"
      enableSearch={true}
      enableExport={true}
      data-cy="environmentdetection-discovered-view"
    />
  );
};

export default EnvironmentdetectionDiscoveredView;
