/**
 * Exchange Discovered View
 *
 * Auto-generated discovered data view for Exchange.
 * Displays CSV data from: ExchangeDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module exchange
 * @category collaboration
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Exchange discovered data view component
 */
export const ExchangeDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Exchange"
      csvPath="ExchangeMailboxes.csv"
      title="Exchange"
      description="Exchange mailboxes, distribution groups, and transport rules"
      enableSearch={true}
      enableExport={true}
      data-cy="exchange-discovered-view"
    />
  );
};

export default ExchangeDiscoveredView;


