/**
 * External Identities Discovered View
 *
 * Auto-generated discovered data view for External Identities.
 * Displays CSV data from: ExternalIdentityDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module externalidentity
 * @category identity
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * External Identities discovered data view component
 */
export const ExternalidentityDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="External Identities"
      csvPath="ExternalIdentityDiscovery.csv"
      title="External Identities"
      description="B2B users, guest accounts, and external collaborators"
      enableSearch={true}
      enableExport={true}
      data-cy="externalidentity-discovered-view"
    />
  );
};

export default ExternalidentityDiscoveredView;
