/**
 * File Servers Discovered View
 *
 * Auto-generated discovered data view for File Servers.
 * Displays CSV data from: FileServerDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module fileserver
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * File Servers discovered data view component
 */
export const FileserverDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="File Servers"
      csvPath="FileServerDiscovery.csv"
      title="File Servers"
      description="File server shares, permissions, and storage"
      enableSearch={true}
      enableExport={true}
      data-cy="fileserver-discovered-view"
    />
  );
};

export default FileserverDiscoveredView;
