/**
 * File Systems Discovered View
 *
 * Auto-generated discovered data view for File Systems.
 * Displays CSV data from: FileSystemDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module filesystem
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * File Systems discovered data view component
 */
export const FilesystemDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="File Systems"
      csvPath="FileSystemDiscovery.csv"
      title="File Systems"
      description="File system shares, permissions, and large files"
      enableSearch={true}
      enableExport={true}
      data-cy="filesystem-discovered-view"
    />
  );
};

export default FilesystemDiscoveredView;
