/**
 * GCP Resources Discovered View
 *
 * Auto-generated discovered data view for GCP Resources.
 * Displays CSV data from: GCPDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module gcp
 * @category cloud
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * GCP Resources discovered data view component
 */
export const GcpDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="GCP Resources"
      csvPath="GCPDiscovery.csv"
      title="GCP Resources"
      description="Google Cloud Platform resources and services"
      enableSearch={true}
      enableExport={true}
      data-cy="gcp-discovered-view"
    />
  );
};

export default GcpDiscoveredView;
