/**
 * Group Policies Discovered View
 *
 * Auto-generated discovered data view for Group Policies.
 * Displays CSV data from: GPO_PlaceholderData.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module gpo
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Group Policies discovered data view component
 */
export const GpoDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Group Policies"
      csvPath="GPO_PlaceholderData.csv"
      title="Group Policies"
      description="Active Directory Group Policy Objects and settings"
      enableSearch={true}
      enableExport={true}
      data-cy="gpo-discovered-view"
    />
  );
};

export default GpoDiscoveredView;


