/**
 * Microsoft Graph Discovered View
 *
 * Auto-generated discovered data view for Microsoft Graph.
 * Displays CSV data from: GraphDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module graph
 * @category identity
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Microsoft Graph discovered data view component
 */
export const GraphDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Microsoft Graph"
      csvPath="GraphDiscovery.csv"
      title="Microsoft Graph"
      description="Microsoft Graph API data and relationships"
      enableSearch={true}
      enableExport={true}
      data-cy="graph-discovered-view"
    />
  );
};

export default GraphDiscoveredView;
