/**
 * Infrastructure Discovered View
 *
 * Auto-generated discovered data view for Infrastructure.
 * Displays CSV data from: InfrastructureDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module infrastructure
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Infrastructure discovered data view component
 */
export const InfrastructureDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Infrastructure"
      csvPath="InfrastructureDiscovery.csv"
      title="Infrastructure"
      description="Physical and virtual infrastructure inventory"
      enableSearch={true}
      enableExport={true}
      data-cy="infrastructure-discovered-view"
    />
  );
};

export default InfrastructureDiscoveredView;
