/**
 * Intune Discovered View
 *
 * Auto-generated discovered data view for Intune.
 * Displays CSV data from: IntuneDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module intune
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Intune discovered data view component
 */
export const IntuneDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Intune"
      csvPath="IntuneDiscovery.csv"
      title="Intune"
      description="Microsoft Intune devices and management policies"
      enableSearch={true}
      enableExport={true}
      data-cy="intune-discovered-view"
    />
  );
};

export default IntuneDiscoveredView;
