/**
 * Licensing Discovered View
 *
 * Auto-generated discovered data view for Licensing.
 * Displays CSV data from: LicensingDiscoveryLicensingSubscriptions.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module licensing
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Licensing discovered data view component
 */
export const LicensingDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Licensing"
      csvPath="LicensingDiscoveryLicensingSubscriptions.csv"
      title="Licensing"
      description="Software licenses and subscription assignments"
      enableSearch={true}
      enableExport={true}
      data-cy="licensing-discovered-view"
    />
  );
};

export default LicensingDiscoveredView;
