/**
 * Multi-Domain Forest Discovered View
 *
 * Auto-generated discovered data view for Multi-Domain Forest.
 * Displays CSV data from: MultiDomainForestDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module multidomainforest
 * @category identity
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Multi-Domain Forest discovered data view component
 */
export const MultidomainforestDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Multi-Domain Forest"
      csvPath="MultiDomainForestDiscovery.csv"
      title="Multi-Domain Forest"
      description="Active Directory forest and domain trust relationships"
      enableSearch={true}
      enableExport={true}
      data-cy="multidomainforest-discovered-view"
    />
  );
};

export default MultidomainforestDiscoveredView;
