/**
 * Network Infrastructure Discovered View
 *
 * Auto-generated discovered data view for Network Infrastructure.
 * Displays CSV data from: NetworkInfrastructure_ARPEntry.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module networkinfrastructure
 * @category network
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Network Infrastructure discovered data view component
 */
export const NetworkinfrastructureDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Network Infrastructure"
      csvPath="NetworkInfrastructure_ARPEntry.csv"
      title="Network Infrastructure"
      description="Network devices, routers, switches, and firewall rules"
      enableSearch={true}
      enableExport={true}
      data-cy="networkinfrastructure-discovered-view"
    />
  );
};

export default NetworkinfrastructureDiscoveredView;
