/**
 * Palo Alto Networks Discovered View
 *
 * Auto-generated discovered data view for Palo Alto Networks.
 * Displays CSV data from: PaloAltoDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module paloalto
 * @category security
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Palo Alto Networks discovered data view component
 */
export const PaloaltoDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Palo Alto Networks"
      csvPath="PaloAltoDiscovery.csv"
      title="Palo Alto Networks"
      description="Palo Alto firewall rules, policies, and security zones"
      enableSearch={true}
      enableExport={true}
      data-cy="paloalto-discovered-view"
    />
  );
};

export default PaloaltoDiscoveredView;
