/**
 * Panorama Interrogation Discovered View
 *
 * Auto-generated discovered data view for Panorama Interrogation.
 * Displays CSV data from: PanoramaInterrogationDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module panoramainterrogation
 * @category security
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Panorama Interrogation discovered data view component
 */
export const PanoramainterrogationDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="PanoramaInterrogation"
      csvPath="PanoramaInterrogationDiscovery.csv"
      title="Panorama Interrogation"
      description="Palo Alto Panorama configuration, policies, and device groups"
      enableSearch={true}
      enableExport={true}
      data-cy="panoramainterrogation-discovered-view"
    />
  );
};

export default PanoramainterrogationDiscoveredView;
