/**
 * Physical Servers Discovered View
 *
 * Auto-generated discovered data view for Physical Servers.
 * Displays CSV data from: PhysicalServerDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module physicalserver
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Physical Servers discovered data view component
 */
export const PhysicalserverDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Physical Servers"
      csvPath="PhysicalServerDiscovery.csv"
      title="Physical Servers"
      description="Physical server hardware, BIOS, and storage configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="physicalserver-discovered-view"
    />
  );
};

export default PhysicalserverDiscoveredView;


