/**
 * Power BI Discovered View
 *
 * Auto-generated discovered data view for Power BI.
 * Displays CSV data from: PowerBIDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module powerbi
 * @category data
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Power BI discovered data view component
 */
export const PowerbiDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Power BI"
      csvPath="PowerBIDiscovery.csv"
      title="Power BI"
      description="Power BI workspaces, datasets, and reports"
      enableSearch={true}
      enableExport={true}
      data-cy="powerbi-discovered-view"
    />
  );
};

export default PowerbiDiscoveredView;
