/**
 * Power Platform Discovered View
 *
 * Auto-generated discovered data view for Power Platform.
 * Displays CSV data from: PowerPlatformDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module powerplatform
 * @category collaboration
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Power Platform discovered data view component
 */
export const PowerplatformDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Power Platform"
      csvPath="PowerPlatformDiscovery.csv"
      title="Power Platform"
      description="Power Apps, Power Automate flows, and Power Virtual Agents"
      enableSearch={true}
      enableExport={true}
      data-cy="powerplatform-discovered-view"
    />
  );
};

export default PowerplatformDiscoveredView;
