/**
 * Printers Discovered View
 *
 * Auto-generated discovered data view for Printers.
 * Displays CSV data from: PrintersDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module printers
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Printers discovered data view component
 */
export const PrintersDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Printers"
      csvPath="PrintersDiscovery.csv"
      title="Printers"
      description="Network printers and print queues"
      enableSearch={true}
      enableExport={true}
      data-cy="printers-discovered-view"
    />
  );
};

export default PrintersDiscoveredView;


