/**
 * Scheduled Tasks Discovered View
 *
 * Auto-generated discovered data view for Scheduled Tasks.
 * Displays CSV data from: ScheduledTasksDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module scheduledtasks
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Scheduled Tasks discovered data view component
 */
export const ScheduledtasksDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Scheduled Tasks"
      csvPath="ScheduledTasksDiscovery.csv"
      title="Scheduled Tasks"
      description="Windows scheduled tasks and automation jobs"
      enableSearch={true}
      enableExport={true}
      data-cy="scheduledtasks-discovered-view"
    />
  );
};

export default ScheduledtasksDiscoveredView;
