/**
 * Security Infrastructure Discovered View
 *
 * Auto-generated discovered data view for Security Infrastructure.
 * Displays CSV data from: SecurityInfrastructureDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module securityinfrastructure
 * @category security
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Security Infrastructure discovered data view component
 */
export const SecurityinfrastructureDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Security Infrastructure"
      csvPath="SecurityInfrastructureDiscovery.csv"
      title="Security Infrastructure"
      description="Security devices, IDS/IPS, and security monitoring"
      enableSearch={true}
      enableExport={true}
      data-cy="securityinfrastructure-discovered-view"
    />
  );
};

export default SecurityinfrastructureDiscoveredView;


