/**
 * SQL Server Discovered View
 *
 * Auto-generated discovered data view for SQL Server.
 * Displays CSV data from: SQLServerDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module sqlserver
 * @category data
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * SQL Server discovered data view component
 */
export const SqlserverDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="SQL Server"
      csvPath="SQLServerDiscovery.csv"
      title="SQL Server"
      description="SQL Server instances, databases, and configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="sqlserver-discovered-view"
    />
  );
};

export default SqlserverDiscoveredView;
