/**
 * Storage Arrays Discovered View
 *
 * Auto-generated discovered data view for Storage Arrays.
 * Displays CSV data from: StorageArrayDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module storagearray
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Storage Arrays discovered data view component
 */
export const StoragearrayDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Storage Arrays"
      csvPath="StorageArrayDiscovery.csv"
      title="Storage Arrays"
      description="SAN/NAS storage arrays and volume configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="storagearray-discovered-view"
    />
  );
};

export default StoragearrayDiscoveredView;


