/**
 * Microsoft Teams Discovered View
 *
 * Auto-generated discovered data view for Microsoft Teams.
 * Displays CSV data from: TeamsDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module teams
 * @category collaboration
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Microsoft Teams discovered data view component
 */
export const TeamsDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Microsoft Teams"
      csvPath="TeamsDiscovery.csv"
      title="Microsoft Teams"
      description="Teams channels, members, and chat configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="teams-discovered-view"
    />
  );
};

export default TeamsDiscoveredView;
