/**
 * Virtualization Discovered View
 *
 * Auto-generated discovered data view for Virtualization.
 * Displays CSV data from: VirtualizationDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module virtualization
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * Virtualization discovered data view component
 */
export const VirtualizationDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="Virtualization"
      csvPath="VirtualizationDiscovery.csv"
      title="Virtualization"
      description="Virtual machines, hypervisors, and VM configurations"
      enableSearch={true}
      enableExport={true}
      data-cy="virtualization-discovered-view"
    />
  );
};

export default VirtualizationDiscoveredView;


