/**
 * VMware Discovered View
 *
 * Auto-generated discovered data view for VMware.
 * Displays CSV data from: VMwareDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module vmware
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewWrapper } from '../../components/organisms/DiscoveredViewWrapper';

/**
 * VMware discovered data view component
 */
export const VmwareDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewWrapper
      moduleName="VMware"
      csvPath="VMwareDiscovery.csv"
      title="VMware"
      description="VMware vSphere VMs, hosts, and clusters"
      enableSearch={true}
      enableExport={true}
      data-cy="vmware-discovered-view"
    />
  );
};

export default VmwareDiscoveredView;
