/**
 * Web Server Config Discovered View
 *
 * Auto-generated discovered data view for Web Server Config.
 * Displays CSV data from: WebServerConfigDiscovery.csv
 *
 * @generated by scripts/generate-discovery-views.js
 * @module webserverconfig
 * @category infrastructure
 */

import React from 'react';
import { DiscoveredViewTemplate } from '../../components/organisms/DiscoveredViewTemplate';

/**
 * Web Server Config discovered data view component
 */
export const WebserverconfigDiscoveredView: React.FC = () => {
  return (
    <DiscoveredViewTemplate
      moduleName="Web Server Config"
      csvPath="WebServerConfigDiscovery.csv"
      title="Web Server Config"
      description="IIS/Apache web server configurations and bindings"
      enableSearch={true}
      enableExport={true}
      data-cy="webserverconfig-discovered-view"
    />
  );
};

export default WebserverconfigDiscoveredView;
