using System.Windows.Controls;
using MandADiscoverySuite.ViewModels;

namespace MandADiscoverySuite.Views
{
    /// <summary>
    /// Interaction logic for EmptyStateValidationView.xaml
    /// </summary>
    public partial class EmptyStateValidationView : UserControl
    {
        public EmptyStateValidationView()
        {
            // InitializeComponent(); - This will be generated by WPF
        }

        public EmptyStateValidationView(EmptyStateValidationViewModel viewModel) : this()
        {
            // Set DataContext after initialization
            if (viewModel != null)
            {
                DataContext = viewModel;
            }
        }
    }
}